question_data = [
    {
        "type": "boolean", "difficulty": "medium", "category": "Vehicles",
        "question": "The majority of Subaru vehicles are made in China.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The first true automobile ever made was the 1886 Benz Patent-Motorwagen.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "Arriva is owned by the Deutsche Bahn.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The Japanese Shinkansen beat the French TGV&#039;s speed record for fastest electric rail train.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "Bugatti was an Italian car manufacturer.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "The snowmobile was invented by Canadian Joseph-Armand Bombardier in 1937.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "Ferrari has never made a V10 engine for any of its cars.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "When BMW was established in 1916, it was producing automobiles.",
     "correct_answer": "False", "incorrect_answers": ["True"]}
]
